name: "JFrog Connect Robot CI"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url
          JF_URL: ${{ vars.JF_URL }}

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          JOB_NAME: ${{ github.job }}
          JOB_NUMBER: ${{ github.run_number }}

      - name: Test JFrog CLI
        run: |
          # Ping the server
          jf rt ping

      - name: Build and deploy
        run: |
          echo "JOB_NAME : $env.JOB_NAME"
          echo "JOB_NUMBER : $env:GITHUB_RUN_NUMBER"
          
          jf rt u simulated_vacuum_robot.py alaxconnect-generic-test-local/vacuum_robot/v1/
          jf rt cp simulated_vacuum_robot.py alaxconnect-generic-test-local/vacuum_robot/v1/ alaxconnect-generic-release-local/vacuum_robot/v1/
          jf rt sp alaxconnect-generic-release-local/vacuum_robot/v1/simulated_vacuum_robot.py v1=version
          
