            - name: Setup JFrog CLI
  # You may pin to the exact commit or the version.
  # uses: jfrog/setup-jfrog-cli@040913fd7ac2a2bcb29a7e963ea99e7c309d63e5
  uses: jfrog/setup-jfrog-cli@v4.5.0
  with:
    # JFrog CLI Version
    version: # optional, default is 2.72.2
    # Remote repository in Artifactory pointing to 'https://releases.jfrog.io/artifactory/jfrog-cli'. Use this parameter in case you don't have an Internet access.
    download-repository: # optional
    # Provider Name's value that was set in OpenId Connect integration in the JFrog platform.
    oidc-provider-name: # optional
    # By default, this is the URL of the GitHub repository owner, such as the organization that owns the repository.
    oidc-audience: # optional
    # Set to true to disable the generation of Job Summaries.
    disable-job-summary: # optional, default is false
    # By default, if the workflow completes with collected build-info that has not been published using the jf rt build-publish command, the build-info will be automatically published to Artifactory. Set this to true to disable the automatic publication of build-info at the end of the workflow.
    disable-auto-build-publish: # optional, default is false
    # Custom JFrog CLI configuration server ID to use instead of the default one generated by the action.
    custom-server-id: # optional
          
