name: "JFrog Connect Robot CI"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url
          JF_URL: ${{ vars.JF_URL }}

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          JOB_NAME: ${{ github.job }}
          JOB_NUMBER: ${{ github.run_number }}

      - name: Test JFrog CLI
        run: |
          # Ping the server
          jf rt ping

      - name: Build and deploy
        run: |
          echo "JOB_NAME : ${{ vars.JOB_NAME }}"
          echo "JOB_NAME : ${{ vars.RUNNER }}"
          
          jf rt u simulated_vacuum_robot.py alaxconnect-generic-test-local/vacuum_robot/
          
#          jf rt bpr ${JOB_NAME} ${JOB_NUMBER} alaxconnect-generic-release-local --status=RELEASE --comment=Release_App_robot --source-repo=alaxconnect-generic-test-local --copy=true
      
          
